In [1]:
import os
import sys
sys.path.append(os.path.join(os.path.dirname(os.getcwd()), 'src'))
from pathlib import Path

import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data_path = os.path.join(str(Path(os.getcwd()).parents[1]), 'open-data/data')
print(os.listdir(data_path))
competitions_path = os.path.join(data_path, 'competitions.json')
events_path = os.path.join(data_path, 'events')
lineups_path = os.path.join(data_path, 'lineups')
matches_path = os.path.join(data_path,'matches')

['lineups', 'events', 'competitions.json', 'matches', 'three-sixty']

In [3]:
event_path = os.path.join(events_path, str(3890561) + '.json')
event_dict_list = json.load(open(event_path, 'r'))

In [4]:
event_dict_list[0]

{'id': '41bd60ac-9b2c-4cb8-85aa-23ae71825c1e',
 'index': 1,
 'period': 1,
 'timestamp': '00:00:00.000',
 'minute': 0,
 'second': 0,
 'type': {'id': 35, 'name': 'Starting XI'},
 'possession': 1,
 'possession_team': {'id': 175, 'name': 'Hoffenheim'},
 'play_pattern': {'id': 1, 'name': 'Regular Play'},
 'team': {'id': 175, 'name': 'Hoffenheim'},
 'duration': 0.0,
 'tactics': {'formation': 3421,
  'lineup': [{'player': {'id': 37972, 'name': 'Jens Grahl'},
    'position': {'id': 1, 'name': 'Goalkeeper'},
    'jersey_number': 13},
   {'player': {'id': 5537, 'name': 'Fabian Lukas Schär'},
    'position': {'id': 3, 'name': 'Right Center Back'},
    'jersey_number': 5},
   {'player': {'id': 9396, 'name': 'Ermin Bičakčić'},
    'position': {'id': 4, 'name': 'Center Back'},
    'jersey_number': 4},
   {'player': {'id': 12321, 'name': 'Tobias Strobl'},
    'position': {'id': 5, 'name': 'Left Center Back'},
    'jersey_number': 12},
   {'player': {'id': 9397, 'name': 'Pavel Kadeřábek'},
    'position': {'id': 7, 'name': 'Right Wing Back'},
    'jersey_number': 3},
   {'player': {'id': 26832, 'name': 'Tarik Elyounoussi'},
    'position': {'id': 8, 'name': 'Left Wing Back'},
    'jersey_number': 14},
   {'player': {'id': 8556, 'name': 'Pirmin Schwegler'},
    'position': {'id': 9, 'name': 'Right Defensive Midfield'},
    'jersey_number': 16},
   {'player': {'id': 6039, 'name': 'Sebastian Rudy'},
    'position': {'id': 11, 'name': 'Left Defensive Midfield'},
    'jersey_number': 6},
   {'player': {'id': 8387, 'name': 'Mark Uth'},
    'position': {'id': 18, 'name': 'Right Attacking Midfield'},
    'jersey_number': 19},
   {'player': {'id': 8215, 'name': 'Kevin Volland'},
    'position': {'id': 20, 'name': 'Left Attacking Midfield'},
    'jersey_number': 31},
   {'player': {'id': 5460, 'name': 'Andrej Kramarić'},
    'position': {'id': 23, 'name': 'Center Forward'},
    'jersey_number': 27}]}}

In [ ]:
# 25 positions namely:
# GK - goalkeeper
# RB - right back
# RCB - right center back
# CB - center back
# LCB - left center back
# LB - left back
# RWB - right wing back
# LWB - left wing back
# RDM - right defensive midfield
# CDM - center defensive midfield
# LDM - Left defensive midfield
# RM - Right midfield
# RCM - Right center midfield
# CM - Center midfield
# LCM - left center midfield
# LM - Left midfield
# RW - right wing
# RAM - Right attacking midfield
# CAM - Center attacking midfield
# LAM - Left attacking midfield
# LW - left wing 
# RCF - right center forward
# ST - striker
# LCF - left center forward
# SS - secondary striker

In [9]:
event_dict_list

[{'id': '41bd60ac-9b2c-4cb8-85aa-23ae71825c1e',
  'index': 1,
  'period': 1,
  'timestamp': '00:00:00.000',
  'minute': 0,
  'second': 0,
  'type': {'id': 35, 'name': 'Starting XI'},
  'possession': 1,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 1, 'name': 'Regular Play'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'duration': 0.0,
  'tactics': {'formation': 3421,
   'lineup': [{'player': {'id': 37972, 'name': 'Jens Grahl'},
     'position': {'id': 1, 'name': 'Goalkeeper'},
     'jersey_number': 13},
    {'player': {'id': 5537, 'name': 'Fabian Lukas Schär'},
     'position': {'id': 3, 'name': 'Right Center Back'},
     'jersey_number': 5},
    {'player': {'id': 9396, 'name': 'Ermin Bičakčić'},
     'position': {'id': 4, 'name': 'Center Back'},
     'jersey_number': 4},
    {'player': {'id': 12321, 'name': 'Tobias Strobl'},
     'position': {'id': 5, 'name': 'Left Center Back'},
     'jersey_number': 12},
    {'player': {'id': 9397, 'name': 'Pavel Kadeřábek'},
     'position': {'id': 7, 'name': 'Right Wing Back'},
     'jersey_number': 3},
    {'player': {'id': 26832, 'name': 'Tarik Elyounoussi'},
     'position': {'id': 8, 'name': 'Left Wing Back'},
     'jersey_number': 14},
    {'player': {'id': 8556, 'name': 'Pirmin Schwegler'},
     'position': {'id': 9, 'name': 'Right Defensive Midfield'},
     'jersey_number': 16},
    {'player': {'id': 6039, 'name': 'Sebastian Rudy'},
     'position': {'id': 11, 'name': 'Left Defensive Midfield'},
     'jersey_number': 6},
    {'player': {'id': 8387, 'name': 'Mark Uth'},
     'position': {'id': 18, 'name': 'Right Attacking Midfield'},
     'jersey_number': 19},
    {'player': {'id': 8215, 'name': 'Kevin Volland'},
     'position': {'id': 20, 'name': 'Left Attacking Midfield'},
     'jersey_number': 31},
    {'player': {'id': 5460, 'name': 'Andrej Kramarić'},
     'position': {'id': 23, 'name': 'Center Forward'},
     'jersey_number': 27}]}},
 {'id': 'fbca533d-f3f4-4a86-b4a3-4fcae63592cf',
  'index': 2,
  'period': 1,
  'timestamp': '00:00:00.000',
  'minute': 0,
  'second': 0,
  'type': {'id': 35, 'name': 'Starting XI'},
  'possession': 1,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 1, 'name': 'Regular Play'},
  'team': {'id': 181, 'name': 'Schalke 04'},
  'duration': 0.0,
  'tactics': {'formation': 4141,
   'lineup': [{'player': {'id': 8517, 'name': 'Ralf Fährmann'},
     'position': {'id': 1, 'name': 'Goalkeeper'},
     'jersey_number': 1},
    {'player': {'id': 7016, 'name': 'Benedikt Höwedes'},
     'position': {'id': 2, 'name': 'Right Back'},
     'jersey_number': 4},
    {'player': {'id': 3502, 'name': 'Joël Andre Job Matip'},
     'position': {'id': 3, 'name': 'Right Center Back'},
     'jersey_number': 32},
    {'player': {'id': 16534, 'name': 'Roman Neustädter'},
     'position': {'id': 5, 'name': 'Left Center Back'},
     'jersey_number': 33},
    {'player': {'id': 3510, 'name': 'Sead Kolašinac'},
     'position': {'id': 6, 'name': 'Left Back'},
     'jersey_number': 6},
    {'player': {'id': 6717, 'name': 'Johannes Geis'},
     'position': {'id': 10, 'name': 'Center Defensive Midfield'},
     'jersey_number': 5},
    {'player': {'id': 3053, 'name': 'Leroy Sané'},
     'position': {'id': 12, 'name': 'Right Midfield'},
     'jersey_number': 19},
    {'player': {'id': 8508, 'name': 'Max Meyer'},
     'position': {'id': 13, 'name': 'Right Center Midfield'},
     'jersey_number': 7},
    {'player': {'id': 5242, 'name': 'Younès Belhanda'},
     'position': {'id': 15, 'name': 'Left Center Midfield'},
     'jersey_number': 11},
    {'player': {'id': 3499, 'name': 'Jean-Eric Maxim Choupo-Moting'},
     'position': {'id': 16, 'name': 'Left Midfield'},
     'jersey_number': 13},
    {'player': {'id': 8060, 'name': 'Klaas-Jan Huntelaar'},
     'position': {'id': 23, 'name': 'Center Forward'},
     'jersey_number': 25}]}},
 {'id': 'b15ba6b1-61ac-4d9c-b2a3-096ce31bcf01',
  'index': 3,
  'period': 1,
  'timestamp': '00:00:00.000',
  'minute': 0,
  'second': 0,
  'type': {'id': 18, 'name': 'Half Start'},
  'possession': 1,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 1, 'name': 'Regular Play'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'duration': 0.0,
  'related_events': ['442128f8-2e38-491c-bf1e-b336e91757fa']},
 {'id': '442128f8-2e38-491c-bf1e-b336e91757fa',
  'index': 4,
  'period': 1,
  'timestamp': '00:00:00.000',
  'minute': 0,
  'second': 0,
  'type': {'id': 18, 'name': 'Half Start'},
  'possession': 1,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 1, 'name': 'Regular Play'},
  'team': {'id': 181, 'name': 'Schalke 04'},
  'duration': 0.0,
  'related_events': ['b15ba6b1-61ac-4d9c-b2a3-096ce31bcf01']},
 {'id': '644e16d7-10ca-45f0-8128-fc0055d6f753',
  'index': 5,
  'period': 1,
  'timestamp': '00:00:00.482',
  'minute': 0,
  'second': 0,
  'type': {'id': 30, 'name': 'Pass'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 8387, 'name': 'Mark Uth'},
  'position': {'id': 18, 'name': 'Right Attacking Midfield'},
  'location': [61.0, 40.1],
  'duration': 0.453238,
  'related_events': ['7602c8d9-d988-4eae-bb9f-309fbad4c7c5'],
  'pass': {'recipient': {'id': 5460, 'name': 'Andrej Kramarić'},
   'length': 2.34094,
   'angle': -1.9195673,
   'height': {'id': 1, 'name': 'Ground Pass'},
   'end_location': [60.2, 37.9],
   'body_part': {'id': 38, 'name': 'Left Foot'},
   'type': {'id': 65, 'name': 'Kick Off'}}},
 {'id': '7602c8d9-d988-4eae-bb9f-309fbad4c7c5',
  'index': 6,
  'period': 1,
  'timestamp': '00:00:00.935',
  'minute': 0,
  'second': 0,
  'type': {'id': 42, 'name': 'Ball Receipt*'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 5460, 'name': 'Andrej Kramarić'},
  'position': {'id': 23, 'name': 'Center Forward'},
  'location': [60.2, 37.9],
  'related_events': ['644e16d7-10ca-45f0-8128-fc0055d6f753']},
 {'id': '329a1879-2521-4614-8c68-b4798b0e5d23',
  'index': 7,
  'period': 1,
  'timestamp': '00:00:00.935',
  'minute': 0,
  'second': 0,
  'type': {'id': 43, 'name': 'Carry'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 5460, 'name': 'Andrej Kramarić'},
  'position': {'id': 23, 'name': 'Center Forward'},
  'location': [60.2, 37.9],
  'duration': 0.08,
  'related_events': ['7602c8d9-d988-4eae-bb9f-309fbad4c7c5',
   '77e2ddaf-6de3-49e7-a318-7d765799b543'],
  'carry': {'end_location': [59.4, 38.3]}},
 {'id': '77e2ddaf-6de3-49e7-a318-7d765799b543',
  'index': 8,
  'period': 1,
  'timestamp': '00:00:01.015',
  'minute': 0,
  'second': 1,
  'type': {'id': 30, 'name': 'Pass'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 5460, 'name': 'Andrej Kramarić'},
  'position': {'id': 23, 'name': 'Center Forward'},
  'location': [59.4, 38.3],
  'duration': 1.151865,
  'related_events': ['69e3b0a7-5847-40db-91d5-0e24fb150f63'],
  'pass': {'recipient': {'id': 6039, 'name': 'Sebastian Rudy'},
   'length': 6.685058,
   'angle': 2.536994,
   'height': {'id': 1, 'name': 'Ground Pass'},
   'end_location': [53.9, 42.1],
   'body_part': {'id': 38, 'name': 'Left Foot'}}},
 {'id': '69e3b0a7-5847-40db-91d5-0e24fb150f63',
  'index': 9,
  'period': 1,
  'timestamp': '00:00:02.167',
  'minute': 0,
  'second': 2,
  'type': {'id': 42, 'name': 'Ball Receipt*'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 6039, 'name': 'Sebastian Rudy'},
  'position': {'id': 11, 'name': 'Left Defensive Midfield'},
  'location': [53.9, 42.1],
  'related_events': ['77e2ddaf-6de3-49e7-a318-7d765799b543']},
 {'id': '1b91a029-f722-4b0d-b9d5-53cdc776f9e3',
  'index': 10,
  'period': 1,
  'timestamp': '00:00:02.167',
  'minute': 0,
  'second': 2,
  'type': {'id': 43, 'name': 'Carry'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 6039, 'name': 'Sebastian Rudy'},
  'position': {'id': 11, 'name': 'Left Defensive Midfield'},
  'location': [53.9, 42.1],
  'duration': 0.787612,
  'related_events': ['2c51f271-c812-45af-896b-06f49a14a5bb',
   '69e3b0a7-5847-40db-91d5-0e24fb150f63'],
  'carry': {'end_location': [52.3, 45.2]}},
 {'id': '2c51f271-c812-45af-896b-06f49a14a5bb',
  'index': 11,
  'period': 1,
  'timestamp': '00:00:02.954',
  'minute': 0,
  'second': 2,
  'type': {'id': 30, 'name': 'Pass'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 6039, 'name': 'Sebastian Rudy'},
  'position': {'id': 11, 'name': 'Left Defensive Midfield'},
  'location': [52.3, 45.2],
  'duration': 1.389406,
  'related_events': ['c30d7035-bb00-4012-9b06-2f3135cdf4d6'],
  'pass': {'recipient': {'id': 5537, 'name': 'Fabian Lukas Schär'},
   'length': 24.62194,
   'angle': 2.3906636,
   'height': {'id': 1, 'name': 'Ground Pass'},
   'end_location': [34.3, 62.0],
   'body_part': {'id': 40, 'name': 'Right Foot'}}},
 {'id': 'c30d7035-bb00-4012-9b06-2f3135cdf4d6',
  'index': 12,
  'period': 1,
  'timestamp': '00:00:04.344',
  'minute': 0,
  'second': 4,
  'type': {'id': 42, 'name': 'Ball Receipt*'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 5537, 'name': 'Fabian Lukas Schär'},
  'position': {'id': 3, 'name': 'Right Center Back'},
  'location': [34.3, 62.0],
  'related_events': ['2c51f271-c812-45af-896b-06f49a14a5bb']},
 {'id': '4e93eb34-ac12-4a24-bcfa-e17d853c8951',
  'index': 13,
  'period': 1,
  'timestamp': '00:00:04.344',
  'minute': 0,
  'second': 4,
  'type': {'id': 43, 'name': 'Carry'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 5537, 'name': 'Fabian Lukas Schär'},
  'position': {'id': 3, 'name': 'Right Center Back'},
  'location': [34.3, 62.0],
  'duration': 1.549877,
  'related_events': ['8b29246d-1d69-4f01-abe1-91c22e308620',
   'c30d7035-bb00-4012-9b06-2f3135cdf4d6'],
  'carry': {'end_location': [34.3, 61.9]}},
 {'id': '8b29246d-1d69-4f01-abe1-91c22e308620',
  'index': 14,
  'period': 1,
  'timestamp': '00:00:05.894',
  'minute': 0,
  'second': 5,
  'type': {'id': 30, 'name': 'Pass'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 5537, 'name': 'Fabian Lukas Schär'},
  'position': {'id': 3, 'name': 'Right Center Back'},
  'location': [34.3, 61.9],
  'duration': 2.557696,
  'related_events': ['9b73ba37-f40c-4add-9f68-ab14ad16070e'],
  'pass': {'recipient': {'id': 12321, 'name': 'Tobias Strobl'},
   'length': 38.333797,
   'angle': -1.4872218,
   'height': {'id': 1, 'name': 'Ground Pass'},
   'end_location': [37.5, 23.7],
   'body_part': {'id': 40, 'name': 'Right Foot'}}},
 {'id': '9b73ba37-f40c-4add-9f68-ab14ad16070e',
  'index': 15,
  'period': 1,
  'timestamp': '00:00:08.451',
  'minute': 0,
  'second': 8,
  'type': {'id': 42, 'name': 'Ball Receipt*'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 12321, 'name': 'Tobias Strobl'},
  'position': {'id': 5, 'name': 'Left Center Back'},
  'location': [37.5, 23.7],
  'related_events': ['8b29246d-1d69-4f01-abe1-91c22e308620']},
 {'id': '0d3f0101-1b31-46f2-86d6-67b4df6967db',
  'index': 16,
  'period': 1,
  'timestamp': '00:00:08.451',
  'minute': 0,
  'second': 8,
  'type': {'id': 43, 'name': 'Carry'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 12321, 'name': 'Tobias Strobl'},
  'position': {'id': 5, 'name': 'Left Center Back'},
  'location': [37.5, 23.7],
  'duration': 2.200544,
  'related_events': ['9b73ba37-f40c-4add-9f68-ab14ad16070e',
   'ed35929b-31b4-42bf-8b54-2db442ce478f'],
  'carry': {'end_location': [38.5, 22.2]}},
 {'id': 'ed35929b-31b4-42bf-8b54-2db442ce478f',
  'index': 17,
  'period': 1,
  'timestamp': '00:00:10.652',
  'minute': 0,
  'second': 10,
  'type': {'id': 30, 'name': 'Pass'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 12321, 'name': 'Tobias Strobl'},
  'position': {'id': 5, 'name': 'Left Center Back'},
  'location': [38.5, 22.2],
  'duration': 1.417774,
  'related_events': ['0ab25e43-7b9d-4020-82fe-e45009954fae'],
  'pass': {'recipient': {'id': 9396, 'name': 'Ermin Bičakčić'},
   'length': 13.421252,
   'angle': 1.7053174,
   'height': {'id': 1, 'name': 'Ground Pass'},
   'end_location': [36.7, 35.5],
   'body_part': {'id': 40, 'name': 'Right Foot'}}},
 {'id': '0ab25e43-7b9d-4020-82fe-e45009954fae',
  'index': 18,
  'period': 1,
  'timestamp': '00:00:12.070',
  'minute': 0,
  'second': 12,
  'type': {'id': 42, 'name': 'Ball Receipt*'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 9396, 'name': 'Ermin Bičakčić'},
  'position': {'id': 4, 'name': 'Center Back'},
  'location': [36.7, 35.5],
  'related_events': ['ed35929b-31b4-42bf-8b54-2db442ce478f']},
 {'id': '87748ce9-72e9-4886-9d81-87160ff28fd5',
  'index': 19,
  'period': 1,
  'timestamp': '00:00:12.070',
  'minute': 0,
  'second': 12,
  'type': {'id': 43, 'name': 'Carry'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 9396, 'name': 'Ermin Bičakčić'},
  'position': {'id': 4, 'name': 'Center Back'},
  'location': [36.7, 35.5],
  'duration': 2.32185,
  'related_events': ['0ab25e43-7b9d-4020-82fe-e45009954fae',
   '50c65a61-8f10-4c41-a9a4-c20c785802c2'],
  'carry': {'end_location': [39.6, 32.7]}},
 {'id': '50c65a61-8f10-4c41-a9a4-c20c785802c2',
  'index': 20,
  'period': 1,
  'timestamp': '00:00:14.391',
  'minute': 0,
  'second': 14,
  'type': {'id': 30, 'name': 'Pass'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 9396, 'name': 'Ermin Bičakčić'},
  'position': {'id': 4, 'name': 'Center Back'},
  'location': [39.6, 32.7],
  'duration': 1.778888,
  'related_events': ['4c2177fb-6bcd-4a6a-955b-6f36dc88d04a'],
  'pass': {'recipient': {'id': 12321, 'name': 'Tobias Strobl'},
   'length': 18.365728,
   'angle': -1.1973677,
   'height': {'id': 1, 'name': 'Ground Pass'},
   'end_location': [46.3, 15.6],
   'body_part': {'id': 40, 'name': 'Right Foot'}}},
 {'id': '4c2177fb-6bcd-4a6a-955b-6f36dc88d04a',
  'index': 21,
  'period': 1,
  'timestamp': '00:00:16.170',
  'minute': 0,
  'second': 16,
  'type': {'id': 42, 'name': 'Ball Receipt*'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 12321, 'name': 'Tobias Strobl'},
  'position': {'id': 5, 'name': 'Left Center Back'},
  'location': [46.3, 15.6],
  'related_events': ['50c65a61-8f10-4c41-a9a4-c20c785802c2']},
 {'id': '14cd0258-2ce0-46c3-9604-27ab9755bec5',
  'index': 22,
  'period': 1,
  'timestamp': '00:00:16.170',
  'minute': 0,
  'second': 16,
  'type': {'id': 43, 'name': 'Carry'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 12321, 'name': 'Tobias Strobl'},
  'position': {'id': 5, 'name': 'Left Center Back'},
  'location': [46.3, 15.6],
  'duration': 1.011907,
  'related_events': ['4c2177fb-6bcd-4a6a-955b-6f36dc88d04a',
   '6446461e-3cf8-4ace-9b0f-fdddef874b30'],
  'carry': {'end_location': [47.0, 12.9]}},
 {'id': '6446461e-3cf8-4ace-9b0f-fdddef874b30',
  'index': 23,
  'period': 1,
  'timestamp': '00:00:17.182',
  'minute': 0,
  'second': 17,
  'type': {'id': 30, 'name': 'Pass'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 12321, 'name': 'Tobias Strobl'},
  'position': {'id': 5, 'name': 'Left Center Back'},
  'location': [47.0, 12.9],
  'duration': 1.50372,
  'related_events': ['5d92ff4e-0e89-4979-806a-20050ed21c52'],
  'pass': {'recipient': {'id': 26832, 'name': 'Tarik Elyounoussi'},
   'length': 18.023596,
   'angle': -0.4537224,
   'height': {'id': 1, 'name': 'Ground Pass'},
   'end_location': [63.2, 5.0],
   'body_part': {'id': 40, 'name': 'Right Foot'}}},
 {'id': 'e99486e6-6464-48f0-9c69-0c8c9eb70baf',
  'index': 24,
  'period': 1,
  'timestamp': '00:00:18.655',
  'minute': 0,
  'second': 18,
  'type': {'id': 17, 'name': 'Pressure'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 181, 'name': 'Schalke 04'},
  'player': {'id': 3053, 'name': 'Leroy Sané'},
  'position': {'id': 12, 'name': 'Right Midfield'},
  'location': [55.4, 73.9],
  'duration': 0.598147,
  'related_events': ['5d92ff4e-0e89-4979-806a-20050ed21c52',
   '93d4f8e8-4321-4f03-98d2-01cebd551735',
   '95b6fbbd-6fe3-47e4-9e65-a8c83025347a']},
 {'id': '5d92ff4e-0e89-4979-806a-20050ed21c52',
  'index': 25,
  'period': 1,
  'timestamp': '00:00:18.686',
  'minute': 0,
  'second': 18,
  'type': {'id': 42, 'name': 'Ball Receipt*'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 26832, 'name': 'Tarik Elyounoussi'},
  'position': {'id': 8, 'name': 'Left Wing Back'},
  'location': [63.2, 5.0],
  'under_pressure': True,
  'related_events': ['6446461e-3cf8-4ace-9b0f-fdddef874b30',
   'e99486e6-6464-48f0-9c69-0c8c9eb70baf']},
 {'id': '95b6fbbd-6fe3-47e4-9e65-a8c83025347a',
  'index': 26,
  'period': 1,
  'timestamp': '00:00:18.686',
  'minute': 0,
  'second': 18,
  'type': {'id': 43, 'name': 'Carry'},
  'possession': 2,
  'possession_team': {'id': 175, 'name': 'Hoffenheim'},
  'play_pattern': {'id': 9, 'name': 'From Kick Off'},
  'team': {'id': 175, 'name': 'Hoffenheim'},
  'player': {'id': 26832, 'name': 'Tarik Elyounoussi'},
  'position': {'id': 8, 'name': 'Left Wing Back'},
  'location': [63.2, 5.0],
  'duration': 0.381643,
  'under_pressure': True,
  'related_events': ['5d92ff4e-0e89-4979-806a-20050ed21c52',
   '93d4f8e8-4321-4f03-98d2-01cebd551735',
   'e99486e6-6464-48f0-9c69-0c8c9eb70baf'],
  'carry': {'end_location': [63.5, 3.6]}},
 {'id': '93d4f8e8-4321-4f03-98d2-01cebd551735',
  'index': 27,
  'period': 1,
  'timestamp': '00:00:19.068',
  'minute': 0,
  'second': 19,

In [22]:
competitions_df = pd.read_json(competitions_path)
competitions_df

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2023-08-17T23:51:11.837478,None,None,2023-08-17T23:51:11.837478
1,16,4,Europe,Champions League,male,False,False,2018/2019,2023-03-07T12:20:48.118250,2021-06-13T16:17:31.694,None,2023-03-07T12:20:48.118250
2,16,1,Europe,Champions League,male,False,False,2017/2018,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2021-01-23T21:55:30.425330
3,16,2,Europe,Champions League,male,False,False,2016/2017,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
4,16,27,Europe,Champions League,male,False,False,2015/2016,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
...,...,...,...,...,...,...,...,...,...,...,...,...
62,55,43,Europe,UEFA Euro,male,False,True,2020,2023-02-24T21:26:47.128979,2023-04-27T22:38:34.970148,2023-04-27T22:38:34.970148,2023-02-24T21:26:47.128979
63,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2023-06-18T19:28:39.443883,2021-06-13T16:17:31.694,None,2023-06-18T19:28:39.443883
64,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2023-07-17T21:19:03.032991,2023-07-17T21:21:56.497106,2023-07-17T21:21:56.497106,2023-07-17T21:19:03.032991
65,72,107,International,Women's World Cup,female,False,True,2023,2023-09-01T12:34:19.705316,2023-09-01T12:35:45.762196,2023-09-01T12:35:45.762196,2023-09-01T12:34:19.705316
66,72,30,International,Women's World Cup,female,False,True,2019,2023-07-27T10:33:48.273734,2021-06-13T16:17:31.694,None,2023-07-27T10:33:48.273734

In [23]:
unique_competition_id = competitions_df["competition_id"].unique()
unique_season_id = competitions_df["season_id"].unique()
match_id = []
match_date = []
kick_off = []
competition = []
season = []
home_team = []
away_team = []
home_score = []
away_score = []
match_status = []
match_status_360 = []
last_updated = []
last_updated_360 = []
meta_data = []
match_week = []
competition_stage = []
stadium = []
referee = []


for i in range(len(unique_competition_id)):
    for j in range(len(unique_season_id)):
        train_match_path = os.path.join(matches_path, str(unique_competition_id[i]) + '/' + str(unique_season_id[j]) + '.json')
        if (os.path.exists(train_match_path)):
            train_match_dict = json.load(open(train_match_path, 'r'))
            #try:
            for match in train_match_dict:
              match_id.append(match['match_id'])
              match_date.append(match['match_date'])
              kick_off.append(match['kick_off'])
              competition.append(match['competition'])
              season.append(match['season'])
              home_team.append(match['home_team'])
              away_team.append(match['away_team'])
              home_score.append(match['home_score'])
              away_score.append(match['away_score'])
              match_status.append(match['match_status'])
              match_status_360.append(match['match_status_360'])
              last_updated.append(match['last_updated'])
              last_updated_360.append(match['last_updated_360'])
              meta_data.append(match['metadata'])
              match_week.append(match['match_week'])
              competition_stage.append(match['competition_stage'])
              try: 
                stadium.append(match['stadium'])
              except KeyError:
                stadium.append(np.nan)
              try:
                referee.append(match["referee"])
              except KeyError:
                referee.append(np.nan)
            #except:
            #  print("No information for these competition/seasons")
            #  print(i,j)
            #  continue  #for cases that tthe json files are empty
            
matches_df = pd.DataFrame({'match_id': match_id,
                           'match_date': match_date,
                            'kick_off': kick_off,
                            'competition': competition,
                           'season': season,
                            'home_team': home_team,
                            'away_team': away_team,
                            'home_score': home_score,
                            'away_score': away_score,
                           'match_status': match_status,                           
                          'match_status_360': match_status_360,
                            'last_updated': last_updated,
                            'last_updated_360': last_updated_360,
                          'meta_data': meta_data,
                          'match_week': match_week,
                           'competition_stage': competition_stage,
                          'stadium': stadium,
                          'referee': referee})

matches_df

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,meta_data,match_week,competition_stage,stadium,referee
0,3890561,2016-05-14,15:30:00.000,"{'competition_id': 9, 'country_name': 'Germany...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 175, 'home_team_name': 'Hoffe...","{'away_team_id': 181, 'away_team_name': 'Schal...",1,4,available,unscheduled,2023-07-24T07:47:12.510532,None,"{'data_version': '1.1.0', 'shot_fidelity_versi...",34,"{'id': 1, 'name': 'Regular Season'}","{'id': 4541, 'name': 'PreZero Arena', 'country...","{'id': 186, 'name': 'Felix Brych', 'country': ..."
1,3890505,2016-04-02,15:30:00.000,"{'competition_id': 9, 'country_name': 'Germany...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 169, 'home_team_name': 'Bayer...","{'away_team_id': 184, 'away_team_name': 'Eintr...",1,0,available,unscheduled,2023-08-03T13:14:14.503553,None,"{'data_version': '1.1.0', 'shot_fidelity_versi...",28,"{'id': 1, 'name': 'Regular Season'}","{'id': 4867, 'name': 'Allianz Arena', 'country...","{'id': 1008758, 'name': 'Florian Meyer', 'coun..."
2,3890511,2016-04-08,20:30:00.000,"{'competition_id': 9, 'country_name': 'Germany...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 173, 'home_team_name': 'Herth...","{'away_team_id': 178, 'away_team_name': 'Hanno...",2,2,available,unscheduled,2023-08-06T05:50:38.345688,None,"{'data_version': '1.1.0', 'shot_fidelity_versi...",29,"{'id': 1, 'name': 'Regular Season'}","{'id': 367, 'name': 'Olympiastadion Berlin', '...","{'id': 235, 'name': 'Benjamin Brand', 'country..."
3,3890515,2016-04-09,15:30:00.000,"{'competition_id': 9, 'country_name': 'Germany...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 171, 'home_team_name': 'Hambu...","{'away_team_id': 872, 'away_team_name': 'Darms...",1,2,available,unscheduled,2023-07-18T17:52:17.363623,None,"{'data_version': '1.1.0', 'shot_fidelity_versi...",29,"{'id': 1, 'name': 'Regular Season'}","{'id': 379, 'name': 'Volksparkstadion', 'count...","{'id': 1008767, 'name': 'Peter Sippel', 'count..."
4,3890411,2015-12-20,16:30:00.000,"{'competition_id': 9, 'country_name': 'Germany...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 173, 'home_team_name': 'Herth...","{'away_team_id': 177, 'away_team_name': 'FSV M...",2,0,available,unscheduled,2023-07-16T13:47:06.565811,None,"{'data_version': '1.1.0', 'shot_fidelity_versi...",17,"{'id': 1, 'name': 'Regular Season'}","{'id': 367, 'name': 'Olympiastadion Berlin', '...","{'id': 1008767, 'name': 'Peter Sippel', 'count..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3194,69199,2019-06-27,21:00:00.000,"{'competition_id': 72, 'country_name': 'Intern...","{'season_id': 30, 'season_name': '2019'}","{'home_team_id': 852, 'home_team_name': 'Norwa...","{'away_team_id': 865, 'away_team_name': 'Engla...",0,3,available,scheduled,2023-07-24T21:48:06.945119,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",5,"{'id': 1, 'name': 'Regular Season'}","{'id': 230, 'name': 'Stade Océane', 'country':...","{'id': 1638, 'name': 'Lucila Venegas Montes', ..."
3195,69258,2019-07-02,21:00:00.000,"{'competition_id': 72, 'country_name': 'Intern...","{'season_id': 30, 'season_name': '2019'}","{'home_team_id': 865, 'home_team_name': 'Engla...","{'away_team_id': 1214, 'away_team_name': 'Unit...",1,2,available,scheduled,2023-07-27T10:32:52.092920,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",6,"{'id': 15, 'name': 'Semi-finals'}","{'id': 193, 'name': 'Groupama Stadium', 'count...",NaN
3196,69284,2019-07-03,21:00:00.000,"{'competition_id': 72, 'country_name': 'Intern...","{'season_id': 30, 'season_name': '2019'}","{'home_team_id': 851, 'home_team_name': 'Nethe...","{'away_team_id': 858, 'away_team_name': 'Swede...",1,0,available,scheduled,2023-07-24T21:53:19.994655,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",6,"{'id': 15, 'name': 'Semi-finals'}","{'id': 193, 'name': 'Groupama Stadium', 'count...","{'id': 1627, 'name': 'Marie-Soleil Beaudoin', ..."
3197,69205,2019-06-29,15:00:00.000,"{'competition_id': 72, 'country_name': 'Intern...","{'season_id': 30, 'season_name': '2019'}","{'home_team_id': 855, 'home_team_name': 'Italy...","{'away_team_id': 851, 'away_team_name': 'Nethe...",0,2,available,scheduled,2023-07-24T21:50:29.191689,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",5,"{'id': 1, 'name': 'Regular Season'}","{'id': 231, 'name': 'Stade du Hainaut', 'count...","{'id': 1632, 'name': 'Claudia Umpiérrez', 'cou..."
3198,69161,2019-06-24,18:00:00.000,"{'competition_id': 72, 'country_name': 'Intern...","{'season_id': 30, 'season_name': '2019'}","{'home_team_id': 863, 'home_team_name': 'Spain...","{'away_team_id': 1214, 'away_team_name': 'Unit...",1,2,available,scheduled,2023-07-24T21:45:21.256779,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",4,"{'id': 33, 'name': 'Round of 16'}","{'id': 232, 'name': 'Stade Auguste-Delaune II ...","{'id': 721, 'name': 'Katalin Kulcsar', 'countr..."

In [57]:
event_path = os.path.join(events_path, str(3890561) + '.json')
event_dict_list = json.load(open(event_path, 'r'))

formation = []
tactical_shift = []
for event in event_dict_list:
    if event["type"]["name"] == "Starting XI":
        formation.append(event)
    if event["type"]["name"] == "Tactical Shift":
        tactical_shift.append(event)
        
#print(len(formation))
#print(len(tactical_shift))


# Note there are 2 teams !!!
#for i in formation:
#    print(i["minute"])

for j in tactical_shift:
    if j["team"]["name"] == team_1:
        print("Team 1 change ppl:")
        print(j["minute"])
    if j["team"]["name"] == team_2:
        print("Team 2 change ppl:")
        print(j["minute"])

In [56]:
# Prepare the input data
home_formation = formation[0]["tactics"]["formation"]
away_formation = formation[1]["tactics"]["formation"]
# Formation data for the home team 
[x["position"]["id"] for x in formation[0]["tactics"]["lineup"]]

[1, 2, 3, 5, 6, 9, 11, 17, 19, 21, 23]

In [95]:
id = 3890411
match_from_df = matches_df[matches_df["match_id"] == id]
match_from_df["home_team"].values

array([{'home_team_id': 173, 'home_team_name': 'Hertha Berlin', 'home_team_gender': 'male', 'home_team_group': None, 'country': {'id': 85, 'name': 'Germany'}, 'managers': [{'id': 51, 'name': 'Pál Dárdai', 'nickname': None, 'dob': '1976-03-16', 'country': {'id': 103, 'name': 'Hungary'}}]}],
      dtype=object)

In [100]:
id = 3890411
match_from_df = matches_df[matches_df["match_id"] == id]
home_team = match_from_df["home_team"].values[0]["home_team_name"]
away_team = match_from_df["away_team"].values[0]["away_team_name"]
event_path = os.path.join(events_path, str(id) + '.json')
event_dict_list = json.load(open(event_path, 'r'))

home_formation = []
away_formation = []
home_pos = []
away_pos = []

home_tactical_shift = []
home_minute = []

away_tactical_shift = []
away_minute = []


for event in event_dict_list:
    if event["type"]["name"] == "Starting XI":
        if event["team"]["name"] == home_team:
            home_formation.append(event["tactics"]["formation"])
            home_pos.append([x["position"]["id"] for x in event["tactics"]["lineup"]])
        elif event["team"]["name"] == away_team:
            away_formation.append(event["tactics"]["formation"])
            away_pos.append([x["position"]["id"] for x in event["tactics"]["lineup"]])

    if event["type"]["name"] == "Tactical Shift":
        if event["team"]["name"] == home_team:
            home_tactical_shift.append([event["tactics"]["formation"], [x["position"]["id"] for x in event["tactics"]["lineup"]]])
            home_minute.append(event["minute"])
        elif event["team"]["name"] == away_team:
            away_tactical_shift.append([event["tactics"]["formation"], [x["position"]["id"] for x in event["tactics"]["lineup"]]])
            away_minute.append(event["minute"])

In [103]:
away_tactical_shift

[[4231, [1, 2, 3, 5, 6, 9, 11, 17, 19, 21, 23]]]

In [101]:
away_formation

[442]

In [102]:
away_pos

[[1, 2, 3, 5, 6, 9, 11, 12, 16, 22, 24]]

In [158]:
# Transform all matches into tactics df to feed into the DL model: (report number of events for the home team)
# In total, there are 50 binary classes (only 14 of them are selectetd)
final_match_id = []
final_home_formation = []
final_home_position = [] # Need further separation (defensive = 0, offensive = 1)
final_away_formation = []
final_away_position = [] # Need further separation (defensive = 0, offensive = 1)
final_minute = []
final_ball_possession = [] # Here say rate, let's compute the percentage of possession per actions
final_goals = [] # plus minus if there is a goal

for id in matches_df["match_id"]:
    match_from_df = matches_df[matches_df["match_id"] == id]
    home_team = match_from_df["home_team"].values[0]["home_team_name"]
    away_team = match_from_df["away_team"].values[0]["away_team_name"]
    event_path = os.path.join(events_path, str(id) + '.json')
    event_dict_list = json.load(open(event_path, 'r'))

    # First task:
    current_minute  = 0
    home_possesion = 0
    possesion_total = 0
    current_goals = 0
    idx = 0

    # Second task:



    # General info about the match
    for event in event_dict_list:
        if event["type"]["name"] == "Starting XI":
            if event["team"]["name"] == home_team:
                current_home_formation = event["tactics"]["formation"]
                current_home_pos = [x["position"]["id"] for x in event["tactics"]["lineup"]]
            elif event["team"]["name"] == away_team:
                current_away_formation = event["tactics"]["formation"]
                current_away_pos = [x["position"]["id"] for x in event["tactics"]["lineup"]]

        if event["type"]["name"] == "Tactical Shift":
            # Update the tactics df
            final_match_id.append(id)
            final_home_formation.append(current_home_formation)
            final_home_position.append(current_home_pos)
            final_away_formation.append(current_away_formation)
            final_away_position.append(current_away_pos)
            final_minute.append(current_minute)
            final_ball_possession.append(home_possesion/possesion_total)
            final_goals.append(current_goals)

            # Reset the attributes:
            possesion_calculation = 0
            current_goals = 0
            home_possesion = 0
            possesion_total = 0

            if event["team"]["name"] == home_team:
                # Update the new change for tactics:
                current_home_formation = event["tactics"]["formation"]
                current_home_pos = [x["position"]["id"] for x in event["tactics"]["lineup"]]
                current_minute = event["minute"]
                

            elif event["team"]["name"] == away_team:
                current_away_formation = event["tactics"]["formation"]
                current_away_pos = [x["position"]["id"] for x in event["tactics"]["lineup"]]
                current_minute = event["minute"]
    

        
        if len(event_dict_list) == idx - 1:
            final_home_formation.append(current_home_formation)
            final_home_position.append(current_home_pos)
            final_away_formation.append(current_away_formation)
            final_away_position.append(current_away_pos)
            final_minute.append(current_minute)
            final_ball_possession.append(home_possesion/possesion_total)
            final_goals.append(current_goals)
        

        if event["type"]["name"] == "Own Goal For":
            if event["team"]["name"] == home_team:
                current_goals += 1
            elif event["team"]["name"] == away_team:
                current_goals -= 1
        
        if event["type"]["name"] == "Shot":
            if event["shot"]["outcome"]["name"] == 'Goal':
                if event["team"]["name"] == home_team:
                    current_goals += 1
                elif event["team"]["name"] == away_team:
                    current_goals -= 1
        
    
        if event["possession_team"]["name"] == home_team:
            home_possesion += 1
            possesion_total += 1
        elif event["possession_team"]["name"] == away_team:
            possesion_total += 1

        idx += 1
        

        
tactics_df = pd.DataFrame({'home_formation': final_home_formation,
                           'home_position': final_home_position,
                           'away_formation': final_away_formation,
                           'away_position': final_away_position,
                           'minute': final_minute,
                           'ball_possession': final_ball_possession,
                           'home_goal': final_goals})

In [159]:
tactics_df

,home_formation,home_position,away_formation,away_position,minute,ball_possession,home_goal
0,3421,"[1, 3, 4, 5, 7, 8, 9, 11, 18, 20, 23]",4141,"[1, 2, 3, 5, 6, 10, 12, 13, 15, 16, 23]",0,0.460870,-2
1,433,"[1, 2, 3, 5, 6, 10, 13, 15, 17, 21, 23]",4141,"[1, 2, 3, 5, 6, 10, 12, 13, 15, 16, 23]",26,0.446927,1
2,433,"[1, 2, 3, 5, 6, 10, 13, 15, 17, 21, 23]",4141,"[1, 2, 3, 5, 6, 10, 12, 13, 15, 16, 23]",45,0.413235,-1
3,442,"[1, 2, 3, 5, 6, 9, 11, 12, 16, 22, 24]",4141,"[1, 2, 3, 5, 6, 10, 12, 13, 15, 16, 23]",59,0.423133,-1
4,433,"[1, 2, 3, 5, 6, 10, 13, 15, 17, 21, 23]",343,"[1, 3, 4, 5, 7, 8, 9, 11, 17, 21, 23]",0,0.690789,1
...,...,...,...,...,...,...,...
7729,4231,"[1, 2, 3, 5, 6, 9, 11, 17, 19, 21, 23]",433,"[1, 2, 3, 5, 6, 10, 13, 15, 17, 21, 23]",0,0.594908,-1
7730,4231,"[1, 2, 3, 5, 6, 9, 11, 17, 19, 21, 23]",433,"[1, 2, 3, 5, 6, 10, 13, 15, 17, 21, 23]",62,0.612583,0
7731,4231,"[1, 2, 3, 5, 6, 9, 11, 17, 19, 21, 23]",343,"[1, 3, 4, 5, 7, 8, 13, 15, 17, 21, 23]",73,0.591623,0
7732,442,"[1, 2, 3, 5, 6, 12, 13, 15, 16, 22, 24]",433,"[1, 2, 3, 5, 6, 10, 13, 15, 17, 21, 23]",0,0.351962,-2
7733,433,"[1, 2, 3, 5, 6, 10, 13, 15, 17, 21, 23]",433,"[1, 2, 3, 5, 6, 10, 13, 15, 17, 21, 23]",0,0.347573,0

In [ ]:
# 0 for defensive/ 1 for offensive:

In [104]:
# check pytorch version
import torch
print(torch.__version__)

2.1.1+cu121

In [114]:
event_dict_list[-1]

{'id': 'cb9bf63e-dcca-424f-9a6e-f1f3f2737293',
 'index': 3672,
 'period': 2,
 'timestamp': '00:46:55.505',
 'minute': 91,
 'second': 55,
 'type': {'id': 34, 'name': 'Half End'},
 'possession': 175,
 'possession_team': {'id': 177, 'name': 'FSV Mainz 05'},
 'play_pattern': {'id': 1, 'name': 'Regular Play'},
 'team': {'id': 173, 'name': 'Hertha Berlin'},
 'duration': 0.0,
 'related_events': ['bc1eb52d-9d46-4d9e-b60a-2d296c6287c2']}

In [162]:
id = 3890561	
match_from_df = matches_df[matches_df["match_id"] == id]
home_team = match_from_df["home_team"].values[0]["home_team_name"]
away_team = match_from_df["away_team"].values[0]["away_team_name"]
event_path = os.path.join(events_path, str(id) + '.json')
event_dict_list = json.load(open(event_path, 'r'))

for event in event_dict_list:
    if event["type"]["name"] == "Starting XI":
        print([x["player"]["name"] for x in event["tactics"]["lineup"]])

['Jens Grahl', 'Fabian Lukas Schär', 'Ermin Bičakčić', 'Tobias Strobl', 'Pavel Kadeřábek', 'Tarik Elyounoussi', 'Pirmin Schwegler', 'Sebastian Rudy', 'Mark Uth', 'Kevin Volland', 'Andrej Kramarić']
['Ralf Fährmann', 'Benedikt Höwedes', 'Joël Andre Job Matip', 'Roman Neustädter', 'Sead Kolašinac', 'Johannes Geis', 'Leroy Sané', 'Max Meyer', 'Younès Belhanda', 'Jean-Eric Maxim Choupo-Moting', 'Klaas-Jan Huntelaar']

In [161]:
for event in event_dict_list:
    if event["type"]["name"] == "Own Goal Against":
        print(event)

{'id': 'b261906f-e190-4b95-991b-315345ca5c05', 'index': 3910, 'period': 2, 'timestamp': '00:43:17.228', 'minute': 88, 'second': 17, 'type': {'id': 20, 'name': 'Own Goal Against'}, 'possession': 170, 'possession_team': {'id': 181, 'name': 'Schalke 04'}, 'play_pattern': {'id': 1, 'name': 'Regular Play'}, 'team': {'id': 175, 'name': 'Hoffenheim'}, 'player': {'id': 5537, 'name': 'Fabian Lukas Schär'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'location': [9.5, 33.7], 'duration': 0.0, 'related_events': ['9daf19f2-64b8-4a9b-9244-3a2ac6190699']}

In [140]:
matches_df["match_id"][50:100]

50    3890528
51    3890527
52    3890526
53    3890525
54    3890524
55    3890523
56    3890522
57    3890521
58    3890520
59    3890519
60    3890518
61    3890517
62    3890516
63    3890514
64    3890513
65    3890512
66    3890510
67    3890509
68    3890508
69    3890507
70    3890506
71    3890504
72    3890503
73    3890502
74    3890501
75    3890500
76    3890499
77    3890498
78    3890497
79    3890496
80    3890495
81    3890494
82    3890493
83    3890492
84    3890491
85    3890490
86    3890489
87    3890488
88    3890487
89    3890486
90    3890485
91    3890484
92    3890483
93    3890482
94    3890481
95    3890480
96    3890479
97    3890478
98    3890477
99    3890476
Name: match_id, dtype: int64