In [1]:
import os
import sys
sys.path.append(os.path.join(os.path.dirname(os.getcwd()), 'src'))
from pathlib import Path

import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

The data used in this research is the open data provided by Statsbomb.  
Url: https://github.com/statsbomb/open-data

* Competition and seasons stored in [`competitions.json`](./data/competitions.json).
* Matches for each competition and season, stored in [`matches`](./data/matches/). Each folder within is named for a competition ID, each file is named for a season ID within that competition.
* Events and lineups for each match, stored in [`events`](./data/events/) and [`lineups`](./data/lineups/) respectively. Each file is named for a match ID.

In [2]:
data_path = os.path.join(str(Path(os.getcwd()).parents[1]), 'open-data/data')
print(os.listdir(data_path))
competitions_path = os.path.join(data_path, 'competitions.json')
events_path = os.path.join(data_path, 'events')
lineups_path = os.path.join(data_path, 'lineups')
matches_path = os.path.join(data_path,'matches')

['lineups', 'events', 'competitions.json', 'matches', 'three-sixty']

### Load competition data

In [3]:
competitions_df = pd.read_json(competitions_path)
competitions_df

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2023-08-17T23:51:11.837478,None,None,2023-08-17T23:51:11.837478
1,16,4,Europe,Champions League,male,False,False,2018/2019,2023-03-07T12:20:48.118250,2021-06-13T16:17:31.694,None,2023-03-07T12:20:48.118250
2,16,1,Europe,Champions League,male,False,False,2017/2018,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2021-01-23T21:55:30.425330
3,16,2,Europe,Champions League,male,False,False,2016/2017,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
4,16,27,Europe,Champions League,male,False,False,2015/2016,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
...,...,...,...,...,...,...,...,...,...,...,...,...
62,55,43,Europe,UEFA Euro,male,False,True,2020,2023-02-24T21:26:47.128979,2023-04-27T22:38:34.970148,2023-04-27T22:38:34.970148,2023-02-24T21:26:47.128979
63,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2023-06-18T19:28:39.443883,2021-06-13T16:17:31.694,None,2023-06-18T19:28:39.443883
64,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2023-07-17T21:19:03.032991,2023-07-17T21:21:56.497106,2023-07-17T21:21:56.497106,2023-07-17T21:19:03.032991
65,72,107,International,Women's World Cup,female,False,True,2023,2023-09-01T12:34:19.705316,2023-09-01T12:35:45.762196,2023-09-01T12:35:45.762196,2023-09-01T12:34:19.705316
66,72,30,International,Women's World Cup,female,False,True,2019,2023-07-27T10:33:48.273734,2021-06-13T16:17:31.694,None,2023-07-27T10:33:48.273734

### Load matches from the Champions League as an example

In [4]:
# Get UCL competition_id and season_id from the competitions_df
ucl_ids = competitions_df[competitions_df.competition_name == 'Champions League'][['competition_id', 'season_id']]
print(ucl_ids)

    competition_id  season_id
1               16          4
2               16          1
3               16          2
4               16         27
5               16         26
6               16         25
7               16         24
8               16         23
9               16         22
10              16         21
11              16         41
12              16         39
13              16         37
14              16         44
15              16         76
16              16        277
17              16         71
18              16        276

In [5]:
# Load one match (i.e. season_id=22) from the list:
match_22_path = os.path.join(matches_path, str(ucl_ids.iloc[8, 0]) + '/' + str(ucl_ids.iloc[8, 1]) + '.json')
match_22_dict = json.load(open(match_22_path, 'r'))[0]

match_22_dict

{'match_id': 18236,
 'match_date': '2011-05-28',
 'kick_off': '20:45:00.000',
 'competition': {'competition_id': 16,
  'country_name': 'Europe',
  'competition_name': 'Champions League'},
 'season': {'season_id': 22, 'season_name': '2010/2011'},
 'home_team': {'home_team_id': 217,
  'home_team_name': 'Barcelona',
  'home_team_gender': 'male',
  'home_team_group': None,
  'country': {'id': 214, 'name': 'Spain'},
  'managers': [{'id': 36,
    'name': 'Josep Guardiola i Sala',
    'nickname': 'Pep Guardiola',
    'dob': '1971-01-18',
    'country': {'id': 214, 'name': 'Spain'}}]},
 'away_team': {'away_team_id': 39,
  'away_team_name': 'Manchester United',
  'away_team_gender': 'male',
  'away_team_group': None,
  'country': {'id': 68, 'name': 'England'},
  'managers': [{'id': 790,
    'name': 'Alex Ferguson',
    'nickname': None,
    'dob': '1941-12-31',
    'country': {'id': 201, 'name': 'Scotland'}}]},
 'home_score': 3,
 'away_score': 1,
 'match_status': 'available',
 'match_status_360': 'scheduled',
 'last_updated': '2022-01-26T21:07:11.033473',
 'last_updated_360': '2021-06-13T16:17:31.694',
 'metadata': {'data_version': '1.0.3'},
 'match_week': 1,
 'competition_stage': {'id': 26, 'name': 'Final'},
 'stadium': {'id': 4666,
  'name': 'Wembley Stadium',
  'country': {'id': 68, 'name': 'England'}},
 'referee': {'id': 449,
  'name': 'Viktor Kassai',
  'country': {'id': 103, 'name': 'Hungary'}}}

In [6]:
# Get lineups of that match
match_id = match_22_dict['match_id']
lineup_path = os.path.join(lineups_path, str(match_id) + '.json')
lineup_dict = json.load(open(lineup_path, 'r'))
lineup_dict

[{'team_id': 39,
  'team_name': 'Manchester United',
  'lineup': [{'player_id': 3058,
    'player_name': 'Javier Hernández Balcázar',
    'player_nickname': None,
    'jersey_number': 14,
    'country': {'id': 147, 'name': 'Mexico'},
    'cards': [],
    'positions': [{'position_id': 24,
      'position': 'Left Center Forward',
      'from': '00:00',
      'to': '45:00',
      'from_period': 1,
      'to_period': 2,
      'start_reason': 'Starting XI',
      'end_reason': 'Tactical Shift'},
     {'position_id': 23,
      'position': 'Center Forward',
      'from': '45:00',
      'to': None,
      'from_period': 2,
      'to_period': None,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 3267,
    'player_name': 'Luis Antonio Valencia Mosquera',
    'player_nickname': 'Antonio Valencia',
    'jersey_number': 25,
    'country': {'id': 65, 'name': 'Ecuador'},
    'cards': [],
    'positions': [{'position_id': 17,
      'position': 'Right Wing',
      'from': '00:00',
      'to': '45:00',
      'from_period': 1,
      'to_period': 2,
      'start_reason': 'Starting XI',
      'end_reason': 'Tactical Shift'},
     {'position_id': 12,
      'position': 'Right Midfield',
      'from': '45:00',
      'to': '68:20',
      'from_period': 2,
      'to_period': 2,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Tactical Shift'},
     {'position_id': 2,
      'position': 'Right Back',
      'from': '68:20',
      'to': None,
      'from_period': 2,
      'to_period': None,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 3538,
    'player_name': 'Wayne Mark Rooney',
    'player_nickname': 'Wayne Rooney',
    'jersey_number': 10,
    'country': {'id': 68, 'name': 'England'},
    'cards': [],
    'positions': [{'position_id': 22,
      'position': 'Right Center Forward',
      'from': '00:00',
      'to': '45:00',
      'from_period': 1,
      'to_period': 2,
      'start_reason': 'Starting XI',
      'end_reason': 'Tactical Shift'},
     {'position_id': 25,
      'position': 'Secondary Striker',
      'from': '45:00',
      'to': None,
      'from_period': 2,
      'to_period': None,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 4022,
    'player_name': 'Darren Fletcher',
    'player_nickname': None,
    'jersey_number': 24,
    'country': {'id': 201, 'name': 'Scotland'},
    'cards': [],
    'positions': []},
   {'player_id': 4751,
    'player_name': 'Michael Carrick',
    'player_nickname': None,
    'jersey_number': 16,
    'country': {'id': 68, 'name': 'England'},
    'cards': [{'time': '60:38',
      'card_type': 'Yellow Card',
      'reason': 'Foul Committed',
      'period': 2}],
    'positions': [{'position_id': 11,
      'position': 'Left Defensive Midfield',
      'from': '00:00',
      'to': '45:00',
      'from_period': 1,
      'to_period': 2,
      'start_reason': 'Starting XI',
      'end_reason': 'Tactical Shift'},
     {'position_id': 9,
      'position': 'Right Defensive Midfield',
      'from': '45:00',
      'to': '76:19',
      'from_period': 2,
      'to_period': 2,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Substitution - Off (Tactical)'}]},
   {'player_id': 8281,
    'player_name': 'Luís Carlos Almeida da Cunha',
    'player_nickname': 'Nani',
    'jersey_number': 17,
    'country': {'id': 183, 'name': 'Portugal'},
    'cards': [],
    'positions': [{'position_id': 2,
      'position': 'Right Back',
      'from': '68:18',
      'to': '68:20',
      'from_period': 2,
      'to_period': 2,
      'start_reason': 'Substitution - On (Tactical)',
      'end_reason': 'Tactical Shift'},
     {'position_id': 12,
      'position': 'Right Midfield',
      'from': '68:20',
      'to': None,
      'from_period': 2,
      'to_period': None,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 10958,
    'player_name': 'Chris Smalling',
    'player_nickname': None,
    'jersey_number': 12,
    'country': {'id': 68, 'name': 'England'},
    'cards': [],
    'positions': []},
   {'player_id': 15036,
    'player_name': 'Edwin van der Sar',
    'player_nickname': None,
    'jersey_number': 1,
    'country': {'id': 160, 'name': 'Netherlands'},
    'cards': [],
    'positions': [{'position_id': 1,
      'position': 'Goalkeeper',
      'from': '00:00',
      'to': None,
      'from_period': 1,
      'to_period': None,
      'start_reason': 'Starting XI',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 15665,
    'player_name': 'Michael Owen',
    'player_nickname': None,
    'jersey_number': 7,
    'country': {'id': 68, 'name': 'England'},
    'cards': [],
    'positions': []},
   {'player_id': 15666,
    'player_name': 'Paul Scholes',
    'player_nickname': None,
    'jersey_number': 18,
    'country': {'id': 68, 'name': 'England'},
    'cards': [],
    'positions': [{'position_id': 9,
      'position': 'Right Defensive Midfield',
      'from': '76:19',
      'to': None,
      'from_period': 2,
      'to_period': None,
      'start_reason': 'Substitution - On (Tactical)',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 18239,
    'player_name': 'Fábio Pereira da Silva',
    'player_nickname': 'Fábio',
    'jersey_number': 20,
    'country': {'id': 31, 'name': 'Brazil'},
    'cards': [],
    'positions': [{'position_id': 2,
      'position': 'Right Back',
      'from': '00:00',
      'to': '68:18',
      'from_period': 1,
      'to_period': 2,
      'start_reason': 'Starting XI',
      'end_reason': 'Substitution - Off (Tactical)'}]},
   {'player_id': 20008,
    'player_name': 'Patrice Evra',
    'player_nickname': None,
    'jersey_number': 3,
    'country': {'id': 78, 'name': 'France'},
    'cards': [],
    'positions': [{'position_id': 6,
      'position': 'Left Back',
      'from': '00:00',
      'to': None,
      'from_period': 1,
      'to_period': None,
      'start_reason': 'Starting XI',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 20171,
    'player_name': 'Rio Ferdinand',
    'player_nickname': None,
    'jersey_number': 5,
    'country': {'id': 68, 'name': 'England'},
    'cards': [],
    'positions': [{'position_id': 3,
      'position': 'Right Center Back',
      'from': '00:00',
      'to': None,
      'from_period': 1,
      'to_period': None,
      'start_reason': 'Starting XI',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 20172,
    'player_name': 'Nemanja Vidić',
    'player_nickname': None,
    'jersey_number': 15,
    'country': {'id': 203, 'name': 'Serbia'},
    'cards': [],
    'positions': [{'position_id': 5,
      'position': 'Left Center Back',
      'from': '00:00',
      'to': None,
      'from_period': 1,
      'to_period': None,
      'start_reason': 'Starting XI',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 20173,
    'player_name': 'Ji-Sung Park',
    'player_nickname': 'Park Ji-Sung',
    'jersey_number': 13,
    'country': {'id': 121, 'name': 'Korea\xa0(South)'},
    'cards': [],
    'positions': [{'position_id': 21,
      'position': 'Left Wing',
      'from': '00:00',
      'to': '45:00',
      'from_period': 1,
      'to_period': 2,
      'start_reason': 'Starting XI',
      'end_reason': 'Tactical Shift'},
     {'position_id': 16,
      'position': 'Left Midfield',
      'from': '45:00',
      'to': '62:07',
      'from_period': 2,
      'to_period': 2,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Tactical Shift'},
     {'position_id': 11,
      'position': 'Left Defensive Midfield',
      'from': '62:07',
      'to': None,
      'from_period': 2,
      'to_period': None,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 20175,
    'player_name': 'Ryan Giggs',
    'player_nickname': None,
    'jersey_number': 11,
    'country': {'id': 249, 'name': 'Wales'},
    'cards': [],
    'positions': [{'position_id': 9,
      'position': 'Right Defensive Midfield',
      'from': '00:00',
      'to': '45:00',
      'from_period': 1,
      'to_period': 2,
      'start_reason': 'Starting XI',
      'end_reason': 'Tactical Shift'},
     {'position_id': 11,
      'position': 'Left Defensive Midfield',
      'from': '45:00',
      'to': '62:07',
      'from_period': 2,
      'to_period': 2,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Tactical Shift'},
     {'position_id': 16,
      'position': 'Left Midfield',
      'from': '62:07',
      'to': None,
      'from_period': 2,
      'to_period': None,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 38411,
    'player_name': 'Anderson Luis de Abreu Oliveira',
    'player_nickname': 'Anderson',
    'jersey_number': 8,
    'country': {'id': 31, 'name': 'Brazil'},
    'cards': [],
    'positions': []},
   {'player_id': 40944,
    'player_name': 'Tomasz Kuszczak',
    'player_nickname': None,
    'jersey_number': 29,
    'country': {'id': 182, 'name': 'Poland'},
    'cards': [],
    'positions': []}]},
 {'team_id': 217,
  'team_name': 'Barcelona',
  'lineup': [{'player_id': 3958,
    'player_name': 'Pedro Eliezer Rodríguez Ledesma',
    'player_nickname': 'Pedro',
    'jersey_number': 17,
    'country': {'id': 214, 'name': 'Spain'},
    'cards': [],
    'positions': [{'position_id': 21,
      'position': 'Left Wing',
      'from': '00:00',
      'to': '89:50',
      'from_period': 1,
      'to_period': 2,
      'start_reason': 'Starting XI',
      'end_reason': 'Tactical Shift'},
     {'position_id': 17,
      'position': 'Right Wing',
      'from': '89:50',
      'to': '91:25',
      'from_period': 2,
      'to_period': 2,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Substitution - Off (Tactical)'}]},
   {'player_id': 4324,
    'player_name': 'Daniel Alves da Silva',
    'player_nickname': 'Dani Alves',
    'jersey_number': 2,
    'country': {'id': 31, 'name': 'Brazil'},
    'cards': [{'time': '59:03',
      'card_type': 'Yellow Card',
      'reason': 'Foul Committed',
      'period': 2}],
    'positions': [{'position_id': 2,
      'position': 'Right Back',
      'from': '00:00',
      'to': '87:47',
      'from_period': 1,
      'to_period': 2,
      'start_reason': 'Starting XI',
      'end_reason': 'Substitution - Off (Tactical)'}]},
   {'player_id': 4891,
    'player_name': 'Ibrahim Afellay',
    'player_nickname': None,
    'jersey_number': 20,
    'country': {'id': 160, 'name': 'Netherlands'},
    'cards': [],
    'positions': [{'position_id': 17,
      'position': 'Right Wing',
      'from': '91:25',
      'to': None,
      'from_period': 2,
      'to_period': None,
      'start_reason': 'Substitution - On (Tactical)',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 4913,
    'player_name': 'Bojan Krkíc Pérez',
    'player_nickname': 'Bojan',
    'jersey_number': 9,
    'country': {'id': 214, 'name': 'Spain'},
    'cards': [],
    'positions': []},
   {'player_id': 5203,
    'player_name': 'Sergio Busquets i Burgos',
    'player_nickname': 'Sergio Busquets',
    'jersey_number': 16,
    'country': {'id': 214, 'name': 'Spain'},
    'cards': [],
    'positions': [{'position_id': 10,
      'position': 'Center Defensive Midfield',
      'from': '00:00',
      'to': None,
      'from_period': 1,
      'to_period': None,
      'start_reason': 'Starting XI',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 5208,
    'player_name': 'Thiago Alcântara do Nascimento',
    'player_nickname': 'Thiago Alcântara',
    'jersey_number': 30,
    'country': {'id': 214, 'name': 'Spain'},
    'cards': [],
    'positions': []},
   {'player_id': 5213,
    'player_name': 'Gerard Piqué Bernabéu',
    'player_nickname': 'Gerard Piqué',
    'jersey_number': 3,
    'country': {'id': 214, 'name': 'Spain'},
    'cards': [],
    'positions': [{'position_id': 5,
      'position': 'Left Center Back',
      'from': '00:00',
      'to': None,
      'from_period': 1,
      'to_period': None,
      'start_reason': 'Starting XI',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 5216,
    'player_name': 'Andrés Iniesta Luján',
    'player_nickname': 'Andrés Iniesta',
    'jersey_number': 8,
    'country': {'id': 214, 'name': 'Spain'},
    'cards': [],
    'positions': [{'position_id': 15,
      'position': 'Left Center Midfield',
      'from': '00:00',
      'to': None,
      'from_period': 1,
      'to_period': None,
      'start_reason': 'Starting XI',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 5503,
    'player_name': 'Lionel Andrés Messi Cuccittini',
    'player_nickname': 'Lionel Messi',
    'jersey_number': 10,
    'country': {'id': 11, 'name': 'Argentina'},
    'cards': [],
    'positions': [{'position_id': 17,
      'position': 'Right Wing',
      'from': '00:00',
      'to': '01:13',
      'from_period': 1,
      'to_period': 1,
      'start_reason': 'Starting XI',
      'end_reason': 'Tactical Shift'},
     {'position_id': 23,
      'position': 'Center Forward',
      'from': '01:13',
      'to': None,
      'from_period': 1,
      'to_period': None,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 5506,
    'player_name': 'Javier Alejandro Mascherano',
    'player_nickname': 'Javier Mascherano',
    'jersey_number': 14,
    'country': {'id': 11, 'name': 'Argentina'},
    'cards': [],
    'positions': [{'position_id': 3,
      'position': 'Right Center Back',
      'from': '00:00',
      'to': '87:48',
      'from_period': 1,
      'to_period': 2,
      'start_reason': 'Starting XI',
      'end_reason': 'Tactical Shift'},
     {'position_id': 2,
      'position': 'Right Back',
      'from': '87:48',
      'to': '89:50',
      'from_period': 2,
      'to_period': 2,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Tactical Shift'},
     {'position_id': 3,
      'position': 'Right Center Back',
      'from': '89:50',
      'to': None,
      'from_period': 2,
      'to_period': None,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 6692,
    'player_name': 'Oier Olazábal Paredes',
    'player_nickname': 'Oier Olazábal',
    'jersey_number': 38,
    'country': {'id': 214, 'name': 'Spain'},
    'cards': [],
    'positions': []},
   {'player_id': 12737,
    'player_name': 'David Villa Sánchez',
    'player_nickname': 'David Villa',
    'jersey_number': 7,
    'country': {'id': 214, 'name': 'Spain'},
    'cards': [],
    'positions': [{'position_id': 23,
      'position': 'Center Forward',
      'from': '00:00',
      'to': '01:13',
      'from_period': 1,
      'to_period': 1,
      'start_reason': 'Starting XI',
      'end_reason': 'Tactical Shift'},
     {'position_id': 17,
      'position': 'Right Wing',
      'from': '01:13',
      'to': '85:12',
      'from_period': 1,
      'to_period': 2,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Substitution - Off (Tactical)'}]},
   {'player_id': 20125,
    'player_name': 'Carles Puyol i Saforcada',
    'player_nickname': 'Carles Puyol',
    'jersey_number': 5,
    'country': {'id': 214, 'name': 'Spain'},
    'cards': [],
    'positions': [{'position_id': 2,
      'position': 'Right Back',
      'from': '87:47',
      'to': '87:48',
      'from_period': 2,
      'to_period': 2,
      'start_reason': 'Substitution - On (Tactical)',
      'end_reason': 'Tactical Shift'},
     {'position_id': 3,
      'position': 'Right Center Back',
      'from': '87:48',
      'to': '89:50',
      'from_period': 2,
      'to_period': 2,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Tactical Shift'},
     {'position_id': 2,
      'position': 'Right Back',
      'from': '89:50',
      'to': None,
      'from_period': 2,
      'to_period': None,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 20131,
    'player_name': 'Xavier Hernández Creus',
    'player_nickname': 'Xavi',
    'jersey_number': 6,
    'country': {'id': 214, 'name': 'Spain'},
    'cards': [],
    'positions': [{'position_id': 13,
      'position': 'Right Center Midfield',
      'from': '00:00',
      'to': None,
      'from_period': 1,
      'to_period': None,
      'start_reason': 'Starting XI',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 20169,
    'player_name': 'Seydou Kéita',
    'player_nickname': 'Seydou Kéita',
    'jersey_number': 15,
    'country': {'id': 140, 'name': 'Mali'},
    'cards': [],
    'positions': [{'position_id': 17,
      'position': 'Right Wing',
      'from': '85:12',
      'to': '89:50',
      'from_period': 2,
      'to_period': 2,
      'start_reason': 'Substitution - On (Tactical)',
      'end_reason': 'Tactical Shift'},
     {'position_id': 21,
      'position': 'Left Wing',
      'from': '89:50',
      'to': None,
      'from_period': 2,
      'to_period': None,
      'start_reason': 'Tactical Shift',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 20176,
    'player_name': 'Víctor Valdés Arribas',
    'player_nickname': 'Víctor Valdés',
    'jersey_number': 1,
    'country': {'id': 214, 'name': 'Spain'},
    'cards': [{'time': '84:56',
      'card_type': 'Yellow Card',
      'reason': 'Bad Behaviour',
      'period': 2}],
    'positions': [{'position_id': 1,
      'position': 'Goalkeeper',
      'from': '00:00',
      'to': None,
      'from_period': 1,
      'to_period': None,
      'start_reason': 'Starting XI',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 20177,
    'player_name': 'Eric-Sylvain Bilal Abidal',
    'player_nickname': 'Éric Abidal',
    'jersey_number': 22,
    'country': {'id': 78, 'name': 'France'},
    'cards': [],
    'positions': [{'position_id': 6,
      'position': 'Left Back',
      'from': '00:00',
      'to': None,
      'from_period': 1,
      'to_period': None,
      'start_reason': 'Starting XI',
      'end_reason': 'Final Whistle'}]},
   {'player_id': 22102,
    'player_name': 'Adriano Correia Claro',
    'player_nickname': 'Adriano',
    'jersey_number': 21,
    'country': {'id': 31, 'name': 'Brazil'},
    'cards': [],
    'positions': []}]}]

In [7]:
# Get events of that match
event_path = os.path.join(events_path, str(match_id) + '.json')
event_dict_list = json.load(open(event_path, 'r'))
event_types_list = []
normal_keys = ['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type', 'possession', 'possession_team', 'play_pattern', 'team']
interested_events = ['Bad Behaviour', 'Ball Receipt*', 'Ball Recovery', 'Block',
       'Carry', 'Clearance', 'Dispossessed', 'Dribble', 'Dribbled Past',
       'Duel', 'Foul Committed', 'Foul Won', 'Goal Keeper',
        'Interception', 'Miscontrol', 'Offside', 'Pass',
       'Pressure', 'Shield', 'Shot',
       'Substitution', 'Tactical Shift']
happened_events = []
for event_dict in event_dict_list:
    event_name = event_dict['type']['name']
    event_types_list.append(event_name)
    if event_name not in happened_events: #and event_name in interested_events:
        keep = []
        for event_key in list(event_dict.keys()):
            if event_key not in normal_keys:
                keep.append(event_key)
        
        happened_events.append(event_name)
        print(event_name, *[(key, item) for key, item in event_dict.items() if key not in normal_keys], sep = '\n')
        print('\n')

Starting XI
('duration', 0.0)
('tactics', {'formation': 41221, 'lineup': [{'player': {'id': 20176, 'name': 'Víctor Valdés Arribas'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'jersey_number': 1}, {'player': {'id': 4324, 'name': 'Daniel Alves da Silva'}, 'position': {'id': 2, 'name': 'Right Back'}, 'jersey_number': 2}, {'player': {'id': 5506, 'name': 'Javier Alejandro Mascherano'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'jersey_number': 14}, {'player': {'id': 5213, 'name': 'Gerard Piqué Bernabéu'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'jersey_number': 3}, {'player': {'id': 20177, 'name': 'Eric-Sylvain Bilal Abidal'}, 'position': {'id': 6, 'name': 'Left Back'}, 'jersey_number': 22}, {'player': {'id': 5203, 'name': 'Sergio Busquets i Burgos'}, 'position': {'id': 10, 'name': 'Center Defensive Midfield'}, 'jersey_number': 16}, {'player': {'id': 20131, 'name': 'Xavier Hernández Creus'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'jersey_number': 6}, {'player': {'id': 5216, 'name': 'Andrés Iniesta Luján'}, 'position': {'id': 15, 'name': 'Left Center Midfield'}, 'jersey_number': 8}, {'player': {'id': 5503, 'name': 'Lionel Andrés Messi Cuccittini'}, 'position': {'id': 17, 'name': 'Right Wing'}, 'jersey_number': 10}, {'player': {'id': 3958, 'name': 'Pedro Eliezer Rodríguez Ledesma'}, 'position': {'id': 21, 'name': 'Left Wing'}, 'jersey_number': 17}, {'player': {'id': 12737, 'name': 'David Villa Sánchez'}, 'position': {'id': 23, 'name': 'Center Forward'}, 'jersey_number': 7}]})


Half Start
('duration', 0.0)
('related_events', ['206bb9ff-6848-4c98-8b81-797aaf24192b'])


Pass
('player', {'id': 3058, 'name': 'Javier Hernández Balcázar'})
('position', {'id': 24, 'name': 'Left Center Forward'})
('location', [61.0, 41.0])
('duration', 0.5809)
('related_events', ['ee82dbf9-b9f5-4eea-84f1-e243d1e97f51'])
('pass', {'recipient': {'id': 3538, 'name': 'Wayne Mark Rooney'}, 'length': 1.4142135, 'angle': 2.3561945, 'height': {'id': 1, 'name': 'Ground Pass'}, 'end_location': [60.0, 42.0], 'type': {'id': 65, 'name': 'Kick Off'}, 'body_part': {'id': 40, 'name': 'Right Foot'}})


Ball Receipt*
('player', {'id': 3538, 'name': 'Wayne Mark Rooney'})
('position', {'id': 22, 'name': 'Right Center Forward'})
('location', [60.0, 42.0])
('related_events', ['a10ce602-229f-4c8a-8c61-95f8e7438a4a'])


Carry
('player', {'id': 3538, 'name': 'Wayne Mark Rooney'})
('position', {'id': 22, 'name': 'Right Center Forward'})
('location', [60.0, 42.0])
('duration', 0.04)
('related_events', ['bcce0444-b3f0-45ab-acc7-85b97e846571', 'ee82dbf9-b9f5-4eea-84f1-e243d1e97f51'])
('carry', {'end_location': [60.0, 42.0]})


Pressure
('player', {'id': 5503, 'name': 'Lionel Andrés Messi Cuccittini'})
('position', {'id': 17, 'name': 'Right Wing'})
('location', [58.0, 43.0])
('duration', 0.216133)


Dispossessed
('player', {'id': 4324, 'name': 'Daniel Alves da Silva'})
('position', {'id': 2, 'name': 'Right Back'})
('location', [56.0, 73.0])
('duration', 0.0)
('under_pressure', True)
('related_events', ['b361ce5e-74f8-4e8b-a37d-11deb526271d'])


Duel
('player', {'id': 20173, 'name': 'Ji-Sung Park'})
('position', {'id': 21, 'name': 'Left Wing'})
('location', [65.0, 8.0])
('duration', 0.0)
('under_pressure', True)
('related_events', ['ac4089c5-8360-4f82-9222-765eb292b4df'])
('duel', {'outcome': {'id': 4, 'name': 'Won'}, 'type': {'id': 11, 'name': 'Tackle'}})


Ball Recovery
('player', {'id': 20131, 'name': 'Xavier Hernández Creus'})
('position', {'id': 13, 'name': 'Right Center Midfield'})
('location', [56.0, 55.0])
('duration', 0.0)
('related_events', ['2b721a67-1edc-4909-bafc-99cdd421c222'])


Dribbled Past
('player', {'id': 20175, 'name': 'Ryan Giggs'})
('position', {'id': 9, 'name': 'Right Defensive Midfield'})
('location', [66.0, 27.0])
('duration', 0.0)
('related_events', ['b89e73f5-ecf3-4018-ad6c-5902f7ed00fc', 'f3a0d950-e280-4a00-ac1b-062489d4643c'])


Dribble
('player', {'id': 20131, 'name': 'Xavier Hernández Creus'})
('position', {'id': 13, 'name': 'Right Center Midfield'})
('location', [55.0, 54.0])
('duration', 0.0)
('under_pressure', True)
('related_events', ['84970056-10cd-42e8-b7f3-8b54f9deb838'])
('dribble', {'overrun': True, 'outcome': {'id': 9, 'name': 'Incomplete'}})


Tactical Shift
('duration', 0.0)
('tactics', {'formation': 41221, 'lineup': [{'player': {'id': 20176, 'name': 'Víctor Valdés Arribas'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'jersey_number': 1}, {'player': {'id': 4324, 'name': 'Daniel Alves da Silva'}, 'position': {'id': 2, 'name': 'Right Back'}, 'jersey_number': 2}, {'player': {'id': 5506, 'name': 'Javier Alejandro Mascherano'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'jersey_number': 14}, {'player': {'id': 5213, 'name': 'Gerard Piqué Bernabéu'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'jersey_number': 3}, {'player': {'id': 20177, 'name': 'Eric-Sylvain Bilal Abidal'}, 'position': {'id': 6, 'name': 'Left Back'}, 'jersey_number': 22}, {'player': {'id': 5203, 'name': 'Sergio Busquets i Burgos'}, 'position': {'id': 10, 'name': 'Center Defensive Midfield'}, 'jersey_number': 16}, {'player': {'id': 20131, 'name': 'Xavier Hernández Creus'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'jersey_number': 6}, {'player': {'id': 5216, 'name': 'Andrés Iniesta Luján'}, 'position': {'id': 15, 'name': 'Left Center Midfield'}, 'jersey_number': 8}, {'player': {'id': 12737, 'name': 'David Villa Sánchez'}, 'position': {'id': 17, 'name': 'Right Wing'}, 'jersey_number': 7}, {'player': {'id': 3958, 'name': 'Pedro Eliezer Rodríguez Ledesma'}, 'position': {'id': 21, 'name': 'Left Wing'}, 'jersey_number': 17}, {'player': {'id': 5503, 'name': 'Lionel Andrés Messi Cuccittini'}, 'position': {'id': 23, 'name': 'Center Forward'}, 'jersey_number': 10}]})


Interception
('player', {'id': 3267, 'name': 'Luis Antonio Valencia Mosquera'})
('position', {'id': 17, 'name': 'Right Wing'})
('location', [73.0, 79.0])
('duration', 0.0)
('counterpress', True)
('related_events', ['cb6dd34a-f791-43d6-a0b2-8c705b69b07f'])
('interception', {'outcome': {'id': 4, 'name': 'Won'}})


Block
('player', {'id': 5203, 'name': 'Sergio Busquets i Burgos'})
('position', {'id': 10, 'name': 'Center Defensive Midfield'})
('location', [53.0, 5.0])
('duration', 0.0)
('counterpress', True)
('related_events', ['88de2b43-02c7-4431-802d-8c879487f0d3'])


Shot
('player', {'id': 3058, 'name': 'Javier Hernández Balcázar'})
('position', {'id': 24, 'name': 'Left Center Forward'})
('location', [99.0, 31.0])
('duration', 0.2434)
('related_events', ['79ccac38-c894-478d-9c82-4295da166ad1', 'f51a1eab-dab1-48bf-a161-34a3e04a21d5'])
('shot', {'statsbomb_xg': 0.05095734, 'end_location': [104.0, 34.0], 'key_pass_id': '5ecd1637-4a9a-45c5-b92b-7d5179334b53', 'body_part': {'id': 40, 'name': 'Right Foot'}, 'type': {'id': 87, 'name': 'Open Play'}, 'outcome': {'id': 96, 'name': 'Blocked'}, 'technique': {'id': 93, 'name': 'Normal'}, 'freeze_frame': [{'location': [102.0, 30.0], 'player': {'id': 4324, 'name': 'Daniel Alves da Silva'}, 'position': {'id': 2, 'name': 'Right Back'}, 'teammate': False}, {'location': [83.0, 5.0], 'player': {'id': 12737, 'name': 'David Villa Sánchez'}, 'position': {'id': 17, 'name': 'Right Wing'}, 'teammate': False}, {'location': [102.0, 45.0], 'player': {'id': 3267, 'name': 'Luis Antonio Valencia Mosquera'}, 'position': {'id': 17, 'name': 'Right Wing'}, 'teammate': True}, {'location': [93.0, 18.0], 'player': {'id': 20008, 'name': 'Patrice Evra'}, 'position': {'id': 6, 'name': 'Left Back'}, 'teammate': True}, {'location': [84.0, 38.0], 'player': {'id': 4751, 'name': 'Michael Carrick'}, 'position': {'id': 11, 'name': 'Left Defensive Midfield'}, 'teammate': True}, {'location': [108.0, 25.0], 'player': {'id': 5506, 'name': 'Javier Alejandro Mascherano'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': False}, {'location': [120.0, 40.0], 'player': {'id': 20176, 'name': 'Víctor Valdés Arribas'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'teammate': False}, {'location': [103.0, 25.0], 'player': {'id': 3538, 'name': 'Wayne Mark Rooney'}, 'position': {'id': 22, 'name': 'Right Center Forward'}, 'teammate': True}, {'location': [104.0, 44.0], 'player': {'id': 20177, 'name': 'Eric-Sylvain Bilal Abidal'}, 'position': {'id': 6, 'name': 'Left Back'}, 'teammate': False}, {'location': [104.0, 35.0], 'player': {'id': 5213, 'name': 'Gerard Piqué Bernabéu'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': False}, {'location': [93.0, 29.0], 'player': {'id': 20131, 'name': 'Xavier Hernández Creus'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'teammate': False}, {'location': [95.0, 38.0], 'player': {'id': 5203, 'name': 'Sergio Busquets i Burgos'}, 'position': {'id': 10, 'name': 'Center Defensive Midfield'}, 'teammate': False}, {'location': [81.0, 23.0], 'player': {'id': 20173, 'name': 'Ji-Sung Park'}, 'position': {'id': 21, 'name': 'Left Wing'}, 'teammate': True}, {'location': [87.0, 27.0], 'player': {'id': 20175, 'name': 'Ryan Giggs'}, 'position': {'id': 9, 'name': 'Right Defensive Midfield'}, 'teammate': True}]})


Goal Keeper
('player', {'id': 20176, 'name': 'Víctor Valdés Arribas'})
('position', {'id': 1, 'name': 'Goalkeeper'})
('location', [1.0, 41.0])
('duration', 0.0)
('related_events', ['e8bac22f-e886-4dc6-a15c-87132c905858'])
('goalkeeper', {'end_location': [2.0, 41.0], 'type': {'id': 32, 'name': 'Shot Faced'}, 'position': {'id': 44, 'name': 'Set'}})


Foul Committed
('player', {'id': 18239, 'name': 'Fábio Pereira da Silva'})
('position', {'id': 2, 'name': 'Right Back'})
('location', [73.0, 60.0])
('duration', 0.0)
('related_events', ['27a24c11-c1eb-4d19-881b-d485606182dc'])


Foul Won
('player', {'id': 5216, 'name': 'Andrés Iniesta Luján'})
('position', {'id': 15, 'name': 'Left Center Midfield'})
('location', [48.0, 21.0])
('duration', 0.0)
('under_pressure', True)
('related_events', ['44f20436-6f8b-4169-8837-26bd67e34132'])


Miscontrol
('player', {'id': 5503, 'name': 'Lionel Andrés Messi Cuccittini'})
('position', {'id': 23, 'name': 'Center Forward'})
('location', [66.0, 39.0])
('duration', 0.0)


Clearance
('player', {'id': 20175, 'name': 'Ryan Giggs'})
('position', {'id': 9, 'name': 'Right Defensive Midfield'})
('location', [8.0, 58.0])
('duration', 0.0)
('under_pressure', True)
('related_events', ['16ae6afc-5675-468a-8f39-21844c6a8358', '60e5aec3-0047-4ea3-b3da-492997d2e35a'])
('clearance', {'aerial_won': True})


Shield
('player', {'id': 3538, 'name': 'Wayne Mark Rooney'})
('position', {'id': 22, 'name': 'Right Center Forward'})
('location', [58.0, 3.0])
('duration', 0.0)


Referee Ball-Drop
('location', [64.0, 18.0])
('duration', 0.0)


Half End
('duration', 0.0)
('related_events', ['0b19aee7-d661-4faa-9e3b-ba7c99ac13c5'])


Offside
('player', {'id': 20177, 'name': 'Eric-Sylvain Bilal Abidal'})
('position', {'id': 6, 'name': 'Left Back'})
('location', [117.0, 16.0])
('duration', 0.0)


Substitution
('player', {'id': 18239, 'name': 'Fábio Pereira da Silva'})
('position', {'id': 2, 'name': 'Right Back'})
('duration', 0.0)
('substitution', {'outcome': {'id': 103, 'name': 'Tactical'}, 'replacement': {'id': 8281, 'name': 'Luís Carlos Almeida da Cunha'}})


Bad Behaviour
('player', {'id': 20176, 'name': 'Víctor Valdés Arribas'})
('position', {'id': 1, 'name': 'Goalkeeper'})
('duration', 0.0)
('bad_behaviour', {'card': {'id': 7, 'name': 'Yellow Card'}})

In [12]:
# Seeing all competitions and then figure the matches logic to extract IDs from each competition:
print("Unique competition IDs:")
print(competitions_df["competition_id"].unique())
print("Unique season IDs:")
print(competitions_df["season_id"].unique())

Unique competition IDs:
[   9   16   87   37 1470   43 1238   11   81    7  116   49    2   12
   55   35   53   72]
Unique season IDs:
[ 27   4   1   2  26  25  24  23  22  21  41  39  37  44  76 277  71 276
  84 268 279  90  42 274 106   3  55  54  51 272 270 269 108  40  38 278
  48 275  68  86  43  75 107  30]

In [53]:
unique_competition_id = competitions_df["competition_id"].unique()
unique_season_id = competitions_df["season_id"].unique()

test_match_path = os.path.join(matches_path, str(unique_competition_id[1]) + '/' + str(unique_season_id[1]) + '.json')
test_match_dict = json.load(open(test_match_path, 'r'))[0]

test_match_path_2 = os.path.join(matches_path, str(unique_competition_id[0]) + '/' + str(unique_season_id[0]) + '.json')
test_match_dict_2 = json.load(open(test_match_path_2, 'r'))[0]

test_match_dict_2

{'match_id': 3890561,
 'match_date': '2016-05-14',
 'kick_off': '15:30:00.000',
 'competition': {'competition_id': 9,
  'country_name': 'Germany',
  'competition_name': '1. Bundesliga'},
 'season': {'season_id': 27, 'season_name': '2015/2016'},
 'home_team': {'home_team_id': 175,
  'home_team_name': 'Hoffenheim',
  'home_team_gender': 'male',
  'home_team_group': None,
  'country': {'id': 85, 'name': 'Germany'},
  'managers': [{'id': 445,
    'name': 'Julian Nagelsmann',
    'nickname': None,
    'dob': '1987-07-23',
    'country': {'id': 85, 'name': 'Germany'}}]},
 'away_team': {'away_team_id': 181,
  'away_team_name': 'Schalke 04',
  'away_team_gender': 'male',
  'away_team_group': None,
  'country': {'id': 85, 'name': 'Germany'},
  'managers': [{'id': 58,
    'name': 'André Breitenreiter',
    'nickname': None,
    'dob': '1973-10-02',
    'country': {'id': 85, 'name': 'Germany'}}]},
 'home_score': 1,
 'away_score': 4,
 'match_status': 'available',
 'match_status_360': 'unscheduled',
 'last_updated': '2023-07-24T07:47:12.510532',
 'last_updated_360': None,
 'metadata': {'data_version': '1.1.0',
  'shot_fidelity_version': '2',
  'xy_fidelity_version': '2'},
 'match_week': 34,
 'competition_stage': {'id': 1, 'name': 'Regular Season'},
 'stadium': {'id': 4541,
  'name': 'PreZero Arena',
  'country': {'id': 85, 'name': 'Germany'}},
 'referee': {'id': 186,
  'name': 'Felix Brych',
  'country': {'id': 85, 'name': 'Germany'}}}

In [54]:
len(test_match_dict_2)

18

In [49]:
column_names = test_match_dict.keys()
len(column_names)

18

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,metadata,match_week,competition_stage,stadium,referee
0,22912,2019-06-01,21:00:00.000,"{'competition_id': 16, 'country_name': 'Europe...","{'season_id': 4, 'season_name': '2018/2019'}","{'home_team_id': 38, 'home_team_name': 'Totten...","{'away_team_id': 24, 'away_team_name': 'Liverp...",0,2,available,scheduled,2022-11-28T14:45:35.628134,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",13,"{'id': 26, 'name': 'Final'}","{'id': 4654, 'name': ' Estádio Cívitas Metropo...","{'id': 420, 'name': 'Damir Skomina', 'country'..."

In [65]:
test_match_dict["referee"]

{'id': 420,
 'name': 'Damir Skomina',
 'country': {'id': 208, 'name': 'Slovenia'}}

In [97]:
unique_competition_id = competitions_df["competition_id"].unique()
unique_season_id = competitions_df["season_id"].unique()
match_id = []
match_date = []
kick_off = []
competition = []
season = []
home_team = []
away_team = []
home_score = []
away_score = []
match_status = []
match_status_360 = []
last_updated = []
last_updated_360 = []
meta_data = []
match_week = []
competition_stage = []
stadium = []
referee = []


for i in range(len(unique_competition_id)):
    for j in range(len(unique_season_id)):
        train_match_path = os.path.join(matches_path, str(unique_competition_id[i]) + '/' + str(unique_season_id[j]) + '.json')
        if (os.path.exists(train_match_path)):
            try:
              train_match_dict = json.load(open(train_match_path, 'r'))[0]
              match_id.append(train_match_dict['match_id'])
              match_date.append(train_match_dict['match_date'])
              kick_off.append(train_match_dict['kick_off'])
              competition.append(train_match_dict['competition'])
              season.append(train_match_dict['season'])
              home_team.append(train_match_dict['home_team'])
              away_team.append(train_match_dict['away_team'])
              home_score.append(train_match_dict['home_score'])
              away_score.append(train_match_dict['away_score'])
              match_status.append(train_match_dict['match_status'])
              match_status_360.append(train_match_dict['match_status_360'])
              last_updated.append(train_match_dict['last_updated'])
              last_updated_360.append(train_match_dict['last_updated_360'])
              meta_data.append(train_match_dict['metadata'])
              match_week.append(train_match_dict['match_week'])
              competition_stage.append(train_match_dict['competition_stage'])
              stadium.append(train_match_dict['stadium'])
              if (len(list(train_match_dict.keys())) == 18): 
                referee.append(train_match_dict["referee"])
              else:
                print("No referee for this match")
                print(i,j)
                referee.append(None)
            except:
                print("No information for this match")
                print(i,j)
                continue  #for cases that tthe json files are empty
            
matches_df = pd.DataFrame({'match_id': match_id,
                           'match_date': match_date,
                            'kick_off': kick_off,
                            'competition': competition,
                           'season': season,
                            'home_team': home_team,
                            'away_team': away_team,
                            'home_score': home_score,
                            'away_score': away_score,
                           'match_status': match_status,                           
                          'match_status_360': match_status_360,
                            'last_updated': last_updated,
                            'last_updated_360': last_updated_360,
                          'meta_data': meta_data,
                          'match_week': match_week,
                           'competition_stage': competition_stage,
                          'stadium': stadium,
                          'referee': referee})

matches_df

No referee for this match
1 12
No referee for this match
1 13
No information for this match
1 14
No referee for this match
1 15
No referee for this match
5 27
No referee for this match
5 30
No referee for this match
7 0
No referee for this match
7 3
No referee for this match
7 21
No referee for this match
7 22
No referee for this match
7 35
No referee for this match
8 36
No referee for this match
12 13

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,meta_data,match_week,competition_stage,stadium,referee
0,3890561,2016-05-14,15:30:00.000,"{'competition_id': 9, 'country_name': 'Germany...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 175, 'home_team_name': 'Hoffe...","{'away_team_id': 181, 'away_team_name': 'Schal...",1,4,available,unscheduled,2023-07-24T07:47:12.510532,None,"{'data_version': '1.1.0', 'shot_fidelity_versi...",34,"{'id': 1, 'name': 'Regular Season'}","{'id': 4541, 'name': 'PreZero Arena', 'country...","{'id': 186, 'name': 'Felix Brych', 'country': ..."
1,18243,2016-05-28,20:45:00.000,"{'competition_id': 16, 'country_name': 'Europe...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 220, 'home_team_name': 'Real ...","{'away_team_id': 212, 'away_team_name': 'Atlét...",1,1,available,scheduled,2020-07-29T05:00,2021-06-13T16:17:31.694,{'data_version': '1.0.3'},1,"{'id': 26, 'name': 'Final'}","{'id': 388, 'name': 'Stadio Giuseppe Meazza ...","{'id': 728, 'name': 'Mark Clattenburg', 'count..."
2,22912,2019-06-01,21:00:00.000,"{'competition_id': 16, 'country_name': 'Europe...","{'season_id': 4, 'season_name': '2018/2019'}","{'home_team_id': 38, 'home_team_name': 'Totten...","{'away_team_id': 24, 'away_team_name': 'Liverp...",0,2,available,scheduled,2022-11-28T14:45:35.628134,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",13,"{'id': 26, 'name': 'Final'}","{'id': 4654, 'name': ' Estádio Cívitas Metropo...","{'id': 420, 'name': 'Damir Skomina', 'country'..."
3,18245,2018-05-26,20:45:00.000,"{'competition_id': 16, 'country_name': 'Europe...","{'season_id': 1, 'season_name': '2017/2018'}","{'home_team_id': 220, 'home_team_name': 'Real ...","{'away_team_id': 24, 'away_team_name': 'Liverp...",3,1,available,scheduled,2021-01-23T21:55:30.425330,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",7,"{'id': 26, 'name': 'Final'}","{'id': 4222, 'name': 'NSK Olimpiyskyi', 'count...","{'id': 727, 'name': 'Milorad Mažić', 'country'..."
4,18244,2017-06-03,20:45:00.000,"{'competition_id': 16, 'country_name': 'Europe...","{'season_id': 2, 'season_name': '2016/2017'}","{'home_team_id': 224, 'home_team_name': 'Juven...","{'away_team_id': 220, 'away_team_name': 'Real ...",1,4,available,scheduled,2020-07-29T05:00,2021-06-13T16:17:31.694,{'data_version': '1.0.3'},7,"{'id': 26, 'name': 'Final'}","{'id': 113891, 'name': 'Principality Stadium',...","{'id': 186, 'name': 'Felix Brych', 'country': ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,3795108,2021-07-02,18:00:00.000,"{'competition_id': 55, 'country_name': 'Europe...","{'season_id': 43, 'season_name': '2020'}","{'home_team_id': 773, 'home_team_name': 'Switz...","{'away_team_id': 772, 'away_team_name': 'Spain...",1,1,available,available,2022-12-01T16:35:19.064845,2023-04-27T21:55:08.695971,"{'data_version': '1.1.0', 'shot_fidelity_versi...",5,"{'id': 11, 'name': 'Quarter-finals'}","{'id': 4726, 'name': 'Saint-Petersburg Stadium...","{'id': 1, 'name': 'Michael Oliver', 'country':..."
62,3887188,1989-05-03,21:30:00.000,"{'competition_id': 35, 'country_name': 'Europe...","{'season_id': 75, 'season_name': '1988/1989'}","{'home_team_id': 227, 'home_team_name': 'Napol...","{'away_team_id': 174, 'away_team_name': 'VfB S...",2,1,available,unscheduled,2023-06-18T19:28:39.443883,None,"{'data_version': '1.1.0', 'shot_fidelity_versi...",12,"{'id': 26, 'name': 'Final'}","{'id': 117450, 'name': 'Stadio Diego Armando M...","{'id': 1009054, 'name': 'Gerasimos Germanakos'..."
63,3835331,2022-07-13,18:00:00.000,"{'competition_id': 53, 'country_name': 'Europe...","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 858, 'home_team_name': 'Swede...","{'away_team_id': 860, 'away_team_name': 'Switz...",2,1,available,available,2022-12-02T01:23:30.414734,2023-04-14T11:27:39.402579,"{'data_version': '1.1.0', 'shot_fidelity_versi...",2,"{'id': 10, 'name': 'Group Stage'}","{'id': 216, 'name': 'Bramall Lane', 'country':...","{'id': 960, 'name': 'Marta Huerta de Aza', 'co..."
64,3904629,2023-08-16,13:00:00.000,"{'competition_id': 72, 'country_name': 'Intern...","{'season_id': 107, 'season_name': '2023'}","{'home_team_id': 1205, 'home_team_name': 'Aust...","{'away_team_id': 865, 'away_team_name': 'Engla...",1,3,available,available,2023-08-30T11:15:11.306289,2023-08-30T11:17:47.551826,"{'data_version': '1.1.0', 'shot_fidelity_versi...",6,"{'id': 15, 'name': 'Semi-finals'}","{'id': 117593, 'name': 'Accor Stadium', 'count...","{'id': 1171, 'name': 'Tori Penso', 'country': ..."
65,22949,2019-06-12,18:00:00.000,"{'competition_id': 72, 'country_name': 'Intern...","{'season_id': 30, 'season_name': '2019'}","{'home_team_id': 857, 'home_team_name': 'Germa...","{'away_team_id': 863, 'away_team_name': 'Spain...",1,0,available,scheduled,2023-07-24T21:46:41.279089,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",2,"{'id': 1, 'name': 'Regular Season'}","{'id': 231, 'name': 'Stade du Hainaut', 'count...","{'id': 374, 'name': 'Kateryna Monzul', 'countr..."

In [88]:
test_match_path = os.path.join(matches_path, str(unique_competition_id[1]) + '/' + str(unique_season_id[12]) + '.json')
test_match_dict = json.load(open(test_match_path, 'r'))[0]
#pd.DataFrame.from_dict(test_match_dict, orient= "index").T
print(len(test_match_dict.keys()))

17

In [80]:
unique_competition_id[1]

16

In [79]:
unique_season_id[14]

76